dist: focal
language: node_js

cache:
  npm: false

jobs:
  include:
    - os: osx
      node_js: 16
    - os: linux
      node_js: 18
    - os: windows
      node_js: 20

script:
  - echo "PRIVATE_KEY=$PRIVATE_KEY" > ./tests/.env
  - npm t
